name: 'Node.js Setup and Install'
description: 'Setup Node.js, cache dependencies, and install dependencies'

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: '20.17.0'
  os-type: # New input to receive runner.os from the workflow
    description: 'Operating system type (e.g., linux, macos, windows)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ inputs.os-type }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ inputs.os-type }}-node-

    - name: Install dependencies
      run: npm ci
      shell: bash
