name: QA

on: pull_request

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

      - name: Format check
        run: npm run format:check

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

      - name: Lint code
        run: npm run lint:nofix

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

      - name: Run tests
        run: npm test
