name: QA

on: pull_request

jobs:
  environment_setup:
    name: Environment setup
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    needs: environment_setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

      - name: Format check
        run: npm run format:check

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: environment_setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

      - name: Lint code
        run: npm run lint:nofix

  tests:
    name: Testing
    runs-on: ubuntu-latest
    needs: environment_setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-action
        with:
          os-type: ${{ runner.os }}

      - name: Run unit tests
        run: npm test

      - name: Run e2e tests
        run: npm run test:e2e
